services:
  vinted-deal-hunter:
    build: .
    image: vinted-deal-hunter:latest
    container_name: vinted-deal-hunter
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - VN_data:/app/data
      - VN_logs:/app/logs
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp

volumes:
  VN_data:
  VN_logs:
